/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddDocumentTagsRequest
 */
export interface AddDocumentTagsRequest {
  /**
   * Array of tags to add to the document
   * @type {Array<string>}
   * @memberof AddDocumentTagsRequest
   */
  tags: Array<string>;
}

/**
 * Check if a given object implements the AddDocumentTagsRequest interface.
 */
export function instanceOfAddDocumentTagsRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'tags' in value;

  return isInstance;
}

export function AddDocumentTagsRequestFromJSON(
  json: any
): AddDocumentTagsRequest {
  return AddDocumentTagsRequestFromJSONTyped(json, false);
}

export function AddDocumentTagsRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AddDocumentTagsRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    tags: json['tags'],
  };
}

export function AddDocumentTagsRequestToJSON(
  value?: AddDocumentTagsRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    tags: value.tags,
  };
}
