/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AnnotationData
 */
export interface AnnotationData {
  [key: string]: any | any;
  /**
   *
   * @type {string}
   * @memberof AnnotationData
   */
  type?: AnnotationDataTypeEnum;
}

/**
 * @export
 */
export const AnnotationDataTypeEnum = {
  Highlight: 'highlight',
  Drawing: 'drawing',
  Bookmark: 'bookmark',
} as const;
export type AnnotationDataTypeEnum =
  (typeof AnnotationDataTypeEnum)[keyof typeof AnnotationDataTypeEnum];

/**
 * Check if a given object implements the AnnotationData interface.
 */
export function instanceOfAnnotationData(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AnnotationDataFromJSON(json: any): AnnotationData {
  return AnnotationDataFromJSONTyped(json, false);
}

export function AnnotationDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnnotationData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...json,
    type: !exists(json, 'type') ? undefined : json['type'],
  };
}

export function AnnotationDataToJSON(value?: AnnotationData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...value,
    type: value.type,
  };
}
