/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BookmarkData } from './BookmarkData';
import {
  instanceOfBookmarkData,
  BookmarkDataFromJSON,
  BookmarkDataFromJSONTyped,
  BookmarkDataToJSON,
} from './BookmarkData';
import type { DrawingData } from './DrawingData';
import {
  instanceOfDrawingData,
  DrawingDataFromJSON,
  DrawingDataFromJSONTyped,
  DrawingDataToJSON,
} from './DrawingData';
import type { HighlightData } from './HighlightData';
import {
  instanceOfHighlightData,
  HighlightDataFromJSON,
  HighlightDataFromJSONTyped,
  HighlightDataToJSON,
} from './HighlightData';

/**
 * @type AnnotationData
 *
 * @export
 */
export type AnnotationData = BookmarkData | DrawingData | HighlightData;

export function AnnotationDataFromJSON(json: any): AnnotationData {
  return AnnotationDataFromJSONTyped(json, false);
}

export function AnnotationDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnnotationData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BookmarkDataFromJSONTyped(json, true),
    ...DrawingDataFromJSONTyped(json, true),
    ...HighlightDataFromJSONTyped(json, true),
  };
}

export function AnnotationDataToJSON(value?: AnnotationData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  if (instanceOfBookmarkData(value)) {
    return BookmarkDataToJSON(value as BookmarkData);
  }
  if (instanceOfDrawingData(value)) {
    return DrawingDataToJSON(value as DrawingData);
  }
  if (instanceOfHighlightData(value)) {
    return HighlightDataToJSON(value as HighlightData);
  }

  return {};
}
