/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BookmarkData
 */
export interface BookmarkData {
  /**
   *
   * @type {string}
   * @memberof BookmarkData
   */
  type: BookmarkDataTypeEnum;
}

/**
 * @export
 */
export const BookmarkDataTypeEnum = {
  Bookmark: 'bookmark',
} as const;
export type BookmarkDataTypeEnum =
  (typeof BookmarkDataTypeEnum)[keyof typeof BookmarkDataTypeEnum];

/**
 * Check if a given object implements the BookmarkData interface.
 */
export function instanceOfBookmarkData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'type' in value;

  return isInstance;
}

export function BookmarkDataFromJSON(json: any): BookmarkData {
  return BookmarkDataFromJSONTyped(json, false);
}

export function BookmarkDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): BookmarkData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json['type'],
  };
}

export function BookmarkDataToJSON(value?: BookmarkData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
  };
}
