/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChatNewMessage200Response
 */
export interface ChatNewMessage200Response {
  /**
   * The AI's response message
   * @type {string}
   * @memberof ChatNewMessage200Response
   */
  message: string;
  /**
   * The chat message id
   * @type {string}
   * @memberof ChatNewMessage200Response
   */
  id: string;
}

/**
 * Check if a given object implements the ChatNewMessage200Response interface.
 */
export function instanceOfChatNewMessage200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'message' in value;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function ChatNewMessage200ResponseFromJSON(
  json: any
): ChatNewMessage200Response {
  return ChatNewMessage200ResponseFromJSONTyped(json, false);
}

export function ChatNewMessage200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChatNewMessage200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: json['message'],
    id: json['id'],
  };
}

export function ChatNewMessage200ResponseToJSON(
  value?: ChatNewMessage200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    id: value.id,
  };
}
