/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  role: string;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  id: string;
}

/**
 * Check if a given object implements the ChatMessage interface.
 */
export function instanceOfChatMessage(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'content' in value;
  isInstance = isInstance && 'role' in value;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function ChatMessageFromJSON(json: any): ChatMessage {
  return ChatMessageFromJSONTyped(json, false);
}

export function ChatMessageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChatMessage {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    content: json['content'],
    role: json['role'],
    id: json['id'],
  };
}

export function ChatMessageToJSON(value?: ChatMessage | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    content: value.content,
    role: value.role,
    id: value.id,
  };
}
