/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChatSpaceKeyMessagePost200Response
 */
export interface ChatSpaceKeyMessagePost200Response {
  /**
   * The AI's response message
   * @type {string}
   * @memberof ChatSpaceKeyMessagePost200Response
   */
  responseMessage?: string;
}

/**
 * Check if a given object implements the ChatSpaceKeyMessagePost200Response interface.
 */
export function instanceOfChatSpaceKeyMessagePost200Response(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ChatSpaceKeyMessagePost200ResponseFromJSON(
  json: any
): ChatSpaceKeyMessagePost200Response {
  return ChatSpaceKeyMessagePost200ResponseFromJSONTyped(json, false);
}

export function ChatSpaceKeyMessagePost200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChatSpaceKeyMessagePost200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    responseMessage: !exists(json, 'responseMessage')
      ? undefined
      : json['responseMessage'],
  };
}

export function ChatSpaceKeyMessagePost200ResponseToJSON(
  value?: ChatSpaceKeyMessagePost200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    responseMessage: value.responseMessage,
  };
}
