/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChatSpaceKeyMessagePostRequest
 */
export interface ChatSpaceKeyMessagePostRequest {
  /**
   * The user's chat message
   * @type {string}
   * @memberof ChatSpaceKeyMessagePostRequest
   */
  message?: string;
  /**
   * The chat session id
   * @type {string}
   * @memberof ChatSpaceKeyMessagePostRequest
   */
  sessionId?: string;
}

/**
 * Check if a given object implements the ChatSpaceKeyMessagePostRequest interface.
 */
export function instanceOfChatSpaceKeyMessagePostRequest(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ChatSpaceKeyMessagePostRequestFromJSON(
  json: any
): ChatSpaceKeyMessagePostRequest {
  return ChatSpaceKeyMessagePostRequestFromJSONTyped(json, false);
}

export function ChatSpaceKeyMessagePostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChatSpaceKeyMessagePostRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    sessionId: !exists(json, 'sessionId') ? undefined : json['sessionId'],
  };
}

export function ChatSpaceKeyMessagePostRequestToJSON(
  value?: ChatSpaceKeyMessagePostRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    sessionId: value.sessionId,
  };
}
