/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChatSettings
 */
export interface ChatSettings {
  /**
   *
   * @type {string}
   * @memberof ChatSettings
   */
  baseUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ChatSettings
   */
  model?: string;
  /**
   *
   * @type {string}
   * @memberof ChatSettings
   */
  apiKeySecretKey: string;
}

/**
 * Check if a given object implements the ChatSettings interface.
 */
export function instanceOfChatSettings(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'apiKeySecretKey' in value;

  return isInstance;
}

export function ChatSettingsFromJSON(json: any): ChatSettings {
  return ChatSettingsFromJSONTyped(json, false);
}

export function ChatSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChatSettings {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    baseUrl: !exists(json, 'baseUrl') ? undefined : json['baseUrl'],
    model: !exists(json, 'model') ? undefined : json['model'],
    apiKeySecretKey: json['apiKeySecretKey'],
  };
}

export function ChatSettingsToJSON(value?: ChatSettings | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    baseUrl: value.baseUrl,
    model: value.model,
    apiKeySecretKey: value.apiKeySecretKey,
  };
}
