/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChatResponseData
 */
export interface ChatResponseData {
  /**
   *
   * @type {string}
   * @memberof ChatResponseData
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof ChatResponseData
   */
  role: string;
  /**
   *
   * @type {string}
   * @memberof ChatResponseData
   */
  id: string;
}

/**
 * Check if a given object implements the ChatResponseData interface.
 */
export function instanceOfChatResponseData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'message' in value;
  isInstance = isInstance && 'role' in value;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function ChatResponseDataFromJSON(json: any): ChatResponseData {
  return ChatResponseDataFromJSONTyped(json, false);
}

export function ChatResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChatResponseData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: json['message'],
    role: json['role'],
    id: json['id'],
  };
}

export function ChatResponseDataToJSON(value?: ChatResponseData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    role: value.role,
    id: value.id,
  };
}
