/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConfirmSignUpRequest
 */
export interface ConfirmSignUpRequest {
  /**
   *
   * @type {string}
   * @memberof ConfirmSignUpRequest
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof ConfirmSignUpRequest
   */
  username: string;
}

/**
 * Check if a given object implements the ConfirmSignUpRequest interface.
 */
export function instanceOfConfirmSignUpRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'code' in value;
  isInstance = isInstance && 'username' in value;

  return isInstance;
}

export function ConfirmSignUpRequestFromJSON(json: any): ConfirmSignUpRequest {
  return ConfirmSignUpRequestFromJSONTyped(json, false);
}

export function ConfirmSignUpRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ConfirmSignUpRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: json['code'],
    username: json['username'],
  };
}

export function ConfirmSignUpRequestToJSON(
  value?: ConfirmSignUpRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code,
    username: value.username,
  };
}
