/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CreateSpaceOperationType = {
  New: 'new',
  Inkstain: 'inkstain',
} as const;
export type CreateSpaceOperationType =
  (typeof CreateSpaceOperationType)[keyof typeof CreateSpaceOperationType];

export function CreateSpaceOperationTypeFromJSON(
  json: any
): CreateSpaceOperationType {
  return CreateSpaceOperationTypeFromJSONTyped(json, false);
}

export function CreateSpaceOperationTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateSpaceOperationType {
  return json as CreateSpaceOperationType;
}

export function CreateSpaceOperationTypeToJSON(
  value?: CreateSpaceOperationType | null
): any {
  return value as any;
}
