/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentTextDetectionDocumentMetadata
 */
export interface DocumentTextDetectionDocumentMetadata {
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionDocumentMetadata
   */
  pages?: number;
}

/**
 * Check if a given object implements the DocumentTextDetectionDocumentMetadata interface.
 */
export function instanceOfDocumentTextDetectionDocumentMetadata(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentTextDetectionDocumentMetadataFromJSON(
  json: any
): DocumentTextDetectionDocumentMetadata {
  return DocumentTextDetectionDocumentMetadataFromJSONTyped(json, false);
}

export function DocumentTextDetectionDocumentMetadataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextDetectionDocumentMetadata {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    pages: !exists(json, 'Pages') ? undefined : json['Pages'],
  };
}

export function DocumentTextDetectionDocumentMetadataToJSON(
  value?: DocumentTextDetectionDocumentMetadata | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Pages: value.pages,
  };
}
