/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentLayoutTextBlockBoundingBox
 */
export interface DocumentLayoutTextBlockBoundingBox {
  /**
   * Ratio to the page width
   * @type {number}
   * @memberof DocumentLayoutTextBlockBoundingBox
   */
  width: number;
  /**
   * Ratio to the page height
   * @type {number}
   * @memberof DocumentLayoutTextBlockBoundingBox
   */
  height: number;
  /**
   * Ratio to the page width
   * @type {number}
   * @memberof DocumentLayoutTextBlockBoundingBox
   */
  left: number;
  /**
   * Ratio to the page height
   * @type {number}
   * @memberof DocumentLayoutTextBlockBoundingBox
   */
  top: number;
}

/**
 * Check if a given object implements the DocumentLayoutTextBlockBoundingBox interface.
 */
export function instanceOfDocumentLayoutTextBlockBoundingBox(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && 'width' in value;
  isInstance = isInstance && 'height' in value;
  isInstance = isInstance && 'left' in value;
  isInstance = isInstance && 'top' in value;

  return isInstance;
}

export function DocumentLayoutTextBlockBoundingBoxFromJSON(
  json: any
): DocumentLayoutTextBlockBoundingBox {
  return DocumentLayoutTextBlockBoundingBoxFromJSONTyped(json, false);
}

export function DocumentLayoutTextBlockBoundingBoxFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentLayoutTextBlockBoundingBox {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    width: json['width'],
    height: json['height'],
    left: json['left'],
    top: json['top'],
  };
}

export function DocumentLayoutTextBlockBoundingBoxToJSON(
  value?: DocumentLayoutTextBlockBoundingBox | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    width: value.width,
    height: value.height,
    left: value.left,
    top: value.top,
  };
}
