/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentTextDetectionBlocksInnerGeometryBoundingBox
 */
export interface DocumentTextDetectionBlocksInnerGeometryBoundingBox {
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInnerGeometryBoundingBox
   */
  height?: number;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInnerGeometryBoundingBox
   */
  left?: number;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInnerGeometryBoundingBox
   */
  top?: number;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInnerGeometryBoundingBox
   */
  width?: number;
}

/**
 * Check if a given object implements the DocumentTextDetectionBlocksInnerGeometryBoundingBox interface.
 */
export function instanceOfDocumentTextDetectionBlocksInnerGeometryBoundingBox(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentTextDetectionBlocksInnerGeometryBoundingBoxFromJSON(
  json: any
): DocumentTextDetectionBlocksInnerGeometryBoundingBox {
  return DocumentTextDetectionBlocksInnerGeometryBoundingBoxFromJSONTyped(
    json,
    false
  );
}

export function DocumentTextDetectionBlocksInnerGeometryBoundingBoxFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextDetectionBlocksInnerGeometryBoundingBox {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    height: !exists(json, 'Height') ? undefined : json['Height'],
    left: !exists(json, 'Left') ? undefined : json['Left'],
    top: !exists(json, 'Top') ? undefined : json['Top'],
    width: !exists(json, 'Width') ? undefined : json['Width'],
  };
}

export function DocumentTextDetectionBlocksInnerGeometryBoundingBoxToJSON(
  value?: DocumentTextDetectionBlocksInnerGeometryBoundingBox | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Height: value.height,
    Left: value.left,
    Top: value.top,
    Width: value.width,
  };
}
