/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentsListPathGet200ResponseInner
 */
export interface DocumentsListPathGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof DocumentsListPathGet200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsListPathGet200ResponseInner
     */
    type?: DocumentsListPathGet200ResponseInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DocumentsListPathGet200ResponseInner
     */
    path?: string;
}


/**
 * @export
 */
export const DocumentsListPathGet200ResponseInnerTypeEnum = {
    Folder: 'folder',
    File: 'file'
} as const;
export type DocumentsListPathGet200ResponseInnerTypeEnum = typeof DocumentsListPathGet200ResponseInnerTypeEnum[keyof typeof DocumentsListPathGet200ResponseInnerTypeEnum];


/**
 * Check if a given object implements the DocumentsListPathGet200ResponseInner interface.
 */
export function instanceOfDocumentsListPathGet200ResponseInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DocumentsListPathGet200ResponseInnerFromJSON(json: any): DocumentsListPathGet200ResponseInner {
    return DocumentsListPathGet200ResponseInnerFromJSONTyped(json, false);
}

export function DocumentsListPathGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsListPathGet200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function DocumentsListPathGet200ResponseInnerToJSON(value?: DocumentsListPathGet200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'path': value.path,
    };
}

