/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentTextDetectionBlocksInnerGeometry } from './DocumentTextDetectionBlocksInnerGeometry';
import {
  DocumentTextDetectionBlocksInnerGeometryFromJSON,
  DocumentTextDetectionBlocksInnerGeometryFromJSONTyped,
  DocumentTextDetectionBlocksInnerGeometryToJSON,
} from './DocumentTextDetectionBlocksInnerGeometry';
import type { DocumentTextDetectionBlocksInnerQuery } from './DocumentTextDetectionBlocksInnerQuery';
import {
  DocumentTextDetectionBlocksInnerQueryFromJSON,
  DocumentTextDetectionBlocksInnerQueryFromJSONTyped,
  DocumentTextDetectionBlocksInnerQueryToJSON,
} from './DocumentTextDetectionBlocksInnerQuery';
import type { DocumentTextDetectionBlocksInnerRelationshipsInner } from './DocumentTextDetectionBlocksInnerRelationshipsInner';
import {
  DocumentTextDetectionBlocksInnerRelationshipsInnerFromJSON,
  DocumentTextDetectionBlocksInnerRelationshipsInnerFromJSONTyped,
  DocumentTextDetectionBlocksInnerRelationshipsInnerToJSON,
} from './DocumentTextDetectionBlocksInnerRelationshipsInner';

/**
 *
 * @export
 * @interface DocumentTextDetectionBlocksInner
 */
export interface DocumentTextDetectionBlocksInner {
  /**
   *
   * @type {string}
   * @memberof DocumentTextDetectionBlocksInner
   */
  blockType?: string;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInner
   */
  columnIndex?: number;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInner
   */
  columnSpan?: number;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInner
   */
  confidence?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof DocumentTextDetectionBlocksInner
   */
  entityTypes?: Array<string>;
  /**
   *
   * @type {DocumentTextDetectionBlocksInnerGeometry}
   * @memberof DocumentTextDetectionBlocksInner
   */
  geometry?: DocumentTextDetectionBlocksInnerGeometry;
  /**
   *
   * @type {string}
   * @memberof DocumentTextDetectionBlocksInner
   */
  id?: string;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInner
   */
  page?: number;
  /**
   *
   * @type {DocumentTextDetectionBlocksInnerQuery}
   * @memberof DocumentTextDetectionBlocksInner
   */
  query?: DocumentTextDetectionBlocksInnerQuery;
  /**
   *
   * @type {Array<DocumentTextDetectionBlocksInnerRelationshipsInner>}
   * @memberof DocumentTextDetectionBlocksInner
   */
  relationships?: Array<DocumentTextDetectionBlocksInnerRelationshipsInner>;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInner
   */
  rowIndex?: number;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionBlocksInner
   */
  rowSpan?: number;
  /**
   *
   * @type {string}
   * @memberof DocumentTextDetectionBlocksInner
   */
  selectionStatus?: string;
  /**
   *
   * @type {string}
   * @memberof DocumentTextDetectionBlocksInner
   */
  text?: string;
  /**
   *
   * @type {string}
   * @memberof DocumentTextDetectionBlocksInner
   */
  textType?: string;
}

/**
 * Check if a given object implements the DocumentTextDetectionBlocksInner interface.
 */
export function instanceOfDocumentTextDetectionBlocksInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentTextDetectionBlocksInnerFromJSON(
  json: any
): DocumentTextDetectionBlocksInner {
  return DocumentTextDetectionBlocksInnerFromJSONTyped(json, false);
}

export function DocumentTextDetectionBlocksInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextDetectionBlocksInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    blockType: !exists(json, 'BlockType') ? undefined : json['BlockType'],
    columnIndex: !exists(json, 'ColumnIndex') ? undefined : json['ColumnIndex'],
    columnSpan: !exists(json, 'ColumnSpan') ? undefined : json['ColumnSpan'],
    confidence: !exists(json, 'Confidence') ? undefined : json['Confidence'],
    entityTypes: !exists(json, 'EntityTypes') ? undefined : json['EntityTypes'],
    geometry: !exists(json, 'Geometry')
      ? undefined
      : DocumentTextDetectionBlocksInnerGeometryFromJSON(json['Geometry']),
    id: !exists(json, 'Id') ? undefined : json['Id'],
    page: !exists(json, 'Page') ? undefined : json['Page'],
    query: !exists(json, 'Query')
      ? undefined
      : DocumentTextDetectionBlocksInnerQueryFromJSON(json['Query']),
    relationships: !exists(json, 'Relationships')
      ? undefined
      : (json['Relationships'] as Array<any>).map(
          DocumentTextDetectionBlocksInnerRelationshipsInnerFromJSON
        ),
    rowIndex: !exists(json, 'RowIndex') ? undefined : json['RowIndex'],
    rowSpan: !exists(json, 'RowSpan') ? undefined : json['RowSpan'],
    selectionStatus: !exists(json, 'SelectionStatus')
      ? undefined
      : json['SelectionStatus'],
    text: !exists(json, 'Text') ? undefined : json['Text'],
    textType: !exists(json, 'TextType') ? undefined : json['TextType'],
  };
}

export function DocumentTextDetectionBlocksInnerToJSON(
  value?: DocumentTextDetectionBlocksInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    BlockType: value.blockType,
    ColumnIndex: value.columnIndex,
    ColumnSpan: value.columnSpan,
    Confidence: value.confidence,
    EntityTypes: value.entityTypes,
    Geometry: DocumentTextDetectionBlocksInnerGeometryToJSON(value.geometry),
    Id: value.id,
    Page: value.page,
    Query: DocumentTextDetectionBlocksInnerQueryToJSON(value.query),
    Relationships:
      value.relationships === undefined
        ? undefined
        : (value.relationships as Array<any>).map(
            DocumentTextDetectionBlocksInnerRelationshipsInnerToJSON
          ),
    RowIndex: value.rowIndex,
    RowSpan: value.rowSpan,
    SelectionStatus: value.selectionStatus,
    Text: value.text,
    TextType: value.textType,
  };
}
