/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentTextDetectionDataInnerGeometryBoundingBox } from './DocumentTextDetectionDataInnerGeometryBoundingBox';
import {
  DocumentTextDetectionDataInnerGeometryBoundingBoxFromJSON,
  DocumentTextDetectionDataInnerGeometryBoundingBoxFromJSONTyped,
  DocumentTextDetectionDataInnerGeometryBoundingBoxToJSON,
} from './DocumentTextDetectionDataInnerGeometryBoundingBox';
import type { DocumentTextDetectionDataInnerGeometryPolygonInner } from './DocumentTextDetectionDataInnerGeometryPolygonInner';
import {
  DocumentTextDetectionDataInnerGeometryPolygonInnerFromJSON,
  DocumentTextDetectionDataInnerGeometryPolygonInnerFromJSONTyped,
  DocumentTextDetectionDataInnerGeometryPolygonInnerToJSON,
} from './DocumentTextDetectionDataInnerGeometryPolygonInner';

/**
 *
 * @export
 * @interface DocumentTextDetectionDataInnerGeometry
 */
export interface DocumentTextDetectionDataInnerGeometry {
  /**
   *
   * @type {DocumentTextDetectionDataInnerGeometryBoundingBox}
   * @memberof DocumentTextDetectionDataInnerGeometry
   */
  boundingBox?: DocumentTextDetectionDataInnerGeometryBoundingBox;
  /**
   *
   * @type {Array<DocumentTextDetectionDataInnerGeometryPolygonInner>}
   * @memberof DocumentTextDetectionDataInnerGeometry
   */
  polygon?: Array<DocumentTextDetectionDataInnerGeometryPolygonInner>;
}

/**
 * Check if a given object implements the DocumentTextDetectionDataInnerGeometry interface.
 */
export function instanceOfDocumentTextDetectionDataInnerGeometry(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentTextDetectionDataInnerGeometryFromJSON(
  json: any
): DocumentTextDetectionDataInnerGeometry {
  return DocumentTextDetectionDataInnerGeometryFromJSONTyped(json, false);
}

export function DocumentTextDetectionDataInnerGeometryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextDetectionDataInnerGeometry {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    boundingBox: !exists(json, 'BoundingBox')
      ? undefined
      : DocumentTextDetectionDataInnerGeometryBoundingBoxFromJSON(
          json['BoundingBox']
        ),
    polygon: !exists(json, 'Polygon')
      ? undefined
      : (json['Polygon'] as Array<any>).map(
          DocumentTextDetectionDataInnerGeometryPolygonInnerFromJSON
        ),
  };
}

export function DocumentTextDetectionDataInnerGeometryToJSON(
  value?: DocumentTextDetectionDataInnerGeometry | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    BoundingBox: DocumentTextDetectionDataInnerGeometryBoundingBoxToJSON(
      value.boundingBox
    ),
    Polygon:
      value.polygon === undefined
        ? undefined
        : (value.polygon as Array<any>).map(
            DocumentTextDetectionDataInnerGeometryPolygonInnerToJSON
          ),
  };
}
