/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentSearchResultMeta } from './DocumentSearchResultMeta';
import {
  DocumentSearchResultMetaFromJSON,
  DocumentSearchResultMetaFromJSONTyped,
  DocumentSearchResultMetaToJSON,
} from './DocumentSearchResultMeta';

/**
 *
 * @export
 * @interface DocumentSearchResult
 */
export interface DocumentSearchResult {
  /**
   *
   * @type {string}
   * @memberof DocumentSearchResult
   */
  documentPath: string;
  /**
   *
   * @type {DocumentSearchResultMeta}
   * @memberof DocumentSearchResult
   */
  meta: DocumentSearchResultMeta;
}

/**
 * Check if a given object implements the DocumentSearchResult interface.
 */
export function instanceOfDocumentSearchResult(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'documentPath' in value;
  isInstance = isInstance && 'meta' in value;

  return isInstance;
}

export function DocumentSearchResultFromJSON(json: any): DocumentSearchResult {
  return DocumentSearchResultFromJSONTyped(json, false);
}

export function DocumentSearchResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentSearchResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    documentPath: json['documentPath'],
    meta: DocumentSearchResultMetaFromJSON(json['meta']),
  };
}

export function DocumentSearchResultToJSON(
  value?: DocumentSearchResult | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    documentPath: value.documentPath,
    meta: DocumentSearchResultMetaToJSON(value.meta),
  };
}
