/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentTextContent
 */
export interface DocumentTextContent {
  /**
   *
   * @type {Array<string>}
   * @memberof DocumentTextContent
   */
  textContent: Array<string>;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof DocumentTextContent
   */
  textBlockToOffset: { [key: string]: number };
}

/**
 * Check if a given object implements the DocumentTextContent interface.
 */
export function instanceOfDocumentTextContent(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'textContent' in value;
  isInstance = isInstance && 'textBlockToOffset' in value;

  return isInstance;
}

export function DocumentTextContentFromJSON(json: any): DocumentTextContent {
  return DocumentTextContentFromJSONTyped(json, false);
}

export function DocumentTextContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextContent {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    textContent: json['textContent'],
    textBlockToOffset: json['textBlockToOffset'],
  };
}

export function DocumentTextContentToJSON(
  value?: DocumentTextContent | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    textContent: value.textContent,
    textBlockToOffset: value.textBlockToOffset,
  };
}
