/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentLayoutTextLineBoundingBox
 */
export interface DocumentLayoutTextLineBoundingBox {
  /**
   *
   * @type {number}
   * @memberof DocumentLayoutTextLineBoundingBox
   */
  width: number;
  /**
   *
   * @type {number}
   * @memberof DocumentLayoutTextLineBoundingBox
   */
  height: number;
  /**
   *
   * @type {number}
   * @memberof DocumentLayoutTextLineBoundingBox
   */
  left: number;
  /**
   *
   * @type {number}
   * @memberof DocumentLayoutTextLineBoundingBox
   */
  top: number;
}

/**
 * Check if a given object implements the DocumentLayoutTextLineBoundingBox interface.
 */
export function instanceOfDocumentLayoutTextLineBoundingBox(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && 'width' in value;
  isInstance = isInstance && 'height' in value;
  isInstance = isInstance && 'left' in value;
  isInstance = isInstance && 'top' in value;

  return isInstance;
}

export function DocumentLayoutTextLineBoundingBoxFromJSON(
  json: any
): DocumentLayoutTextLineBoundingBox {
  return DocumentLayoutTextLineBoundingBoxFromJSONTyped(json, false);
}

export function DocumentLayoutTextLineBoundingBoxFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentLayoutTextLineBoundingBox {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    width: json['width'],
    height: json['height'],
    left: json['left'],
    top: json['top'],
  };
}

export function DocumentLayoutTextLineBoundingBoxToJSON(
  value?: DocumentLayoutTextLineBoundingBox | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    width: value.width,
    height: value.height,
    left: value.left,
    top: value.top,
  };
}
