/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentTextDetectionDataInnerRelationshipsInner
 */
export interface DocumentTextDetectionDataInnerRelationshipsInner {
  /**
   *
   * @type {Array<string>}
   * @memberof DocumentTextDetectionDataInnerRelationshipsInner
   */
  ids?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof DocumentTextDetectionDataInnerRelationshipsInner
   */
  type?: string;
}

/**
 * Check if a given object implements the DocumentTextDetectionDataInnerRelationshipsInner interface.
 */
export function instanceOfDocumentTextDetectionDataInnerRelationshipsInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentTextDetectionDataInnerRelationshipsInnerFromJSON(
  json: any
): DocumentTextDetectionDataInnerRelationshipsInner {
  return DocumentTextDetectionDataInnerRelationshipsInnerFromJSONTyped(
    json,
    false
  );
}

export function DocumentTextDetectionDataInnerRelationshipsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextDetectionDataInnerRelationshipsInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ids: !exists(json, 'Ids') ? undefined : json['Ids'],
    type: !exists(json, 'Type') ? undefined : json['Type'],
  };
}

export function DocumentTextDetectionDataInnerRelationshipsInnerToJSON(
  value?: DocumentTextDetectionDataInnerRelationshipsInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Ids: value.ids,
    Type: value.type,
  };
}
