/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentTextDetectionBlocksInnerQuery
 */
export interface DocumentTextDetectionBlocksInnerQuery {
  /**
   *
   * @type {string}
   * @memberof DocumentTextDetectionBlocksInnerQuery
   */
  alias?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof DocumentTextDetectionBlocksInnerQuery
   */
  pages?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof DocumentTextDetectionBlocksInnerQuery
   */
  text?: string;
}

/**
 * Check if a given object implements the DocumentTextDetectionBlocksInnerQuery interface.
 */
export function instanceOfDocumentTextDetectionBlocksInnerQuery(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentTextDetectionBlocksInnerQueryFromJSON(
  json: any
): DocumentTextDetectionBlocksInnerQuery {
  return DocumentTextDetectionBlocksInnerQueryFromJSONTyped(json, false);
}

export function DocumentTextDetectionBlocksInnerQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextDetectionBlocksInnerQuery {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    alias: !exists(json, 'Alias') ? undefined : json['Alias'],
    pages: !exists(json, 'Pages') ? undefined : json['Pages'],
    text: !exists(json, 'Text') ? undefined : json['Text'],
  };
}

export function DocumentTextDetectionBlocksInnerQueryToJSON(
  value?: DocumentTextDetectionBlocksInnerQuery | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Alias: value.alias,
    Pages: value.pages,
    Text: value.text,
  };
}
