/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentMetaAttributesValue
 */
export interface DocumentMetaAttributesValue {}

/**
 * Check if a given object implements the DocumentMetaAttributesValue interface.
 */
export function instanceOfDocumentMetaAttributesValue(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentMetaAttributesValueFromJSON(
  json: any
): DocumentMetaAttributesValue {
  return DocumentMetaAttributesValueFromJSONTyped(json, false);
}

export function DocumentMetaAttributesValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentMetaAttributesValue {
  return json;
}

export function DocumentMetaAttributesValueToJSON(
  value?: DocumentMetaAttributesValue | null
): any {
  return value;
}
