/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentLayoutTextLineBoundingBox } from './DocumentLayoutTextLineBoundingBox';
import {
  DocumentLayoutTextLineBoundingBoxFromJSON,
  DocumentLayoutTextLineBoundingBoxFromJSONTyped,
  DocumentLayoutTextLineBoundingBoxToJSON,
} from './DocumentLayoutTextLineBoundingBox';

/**
 *
 * @export
 * @interface DocumentLayoutTextLine
 */
export interface DocumentLayoutTextLine {
  /**
   *
   * @type {string}
   * @memberof DocumentLayoutTextLine
   */
  id: string;
  /**
   *
   * @type {DocumentLayoutTextLineBoundingBox}
   * @memberof DocumentLayoutTextLine
   */
  boundingBox: DocumentLayoutTextLineBoundingBox;
}

/**
 * Check if a given object implements the DocumentLayoutTextLine interface.
 */
export function instanceOfDocumentLayoutTextLine(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'boundingBox' in value;

  return isInstance;
}

export function DocumentLayoutTextLineFromJSON(
  json: any
): DocumentLayoutTextLine {
  return DocumentLayoutTextLineFromJSONTyped(json, false);
}

export function DocumentLayoutTextLineFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentLayoutTextLine {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    boundingBox: DocumentLayoutTextLineBoundingBoxFromJSON(json['boundingBox']),
  };
}

export function DocumentLayoutTextLineToJSON(
  value?: DocumentLayoutTextLine | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    boundingBox: DocumentLayoutTextLineBoundingBoxToJSON(value.boundingBox),
  };
}
