/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentTextDetectionBlocksInnerGeometryBoundingBox } from './DocumentTextDetectionBlocksInnerGeometryBoundingBox';
import {
  DocumentTextDetectionBlocksInnerGeometryBoundingBoxFromJSON,
  DocumentTextDetectionBlocksInnerGeometryBoundingBoxFromJSONTyped,
  DocumentTextDetectionBlocksInnerGeometryBoundingBoxToJSON,
} from './DocumentTextDetectionBlocksInnerGeometryBoundingBox';
import type { DocumentTextDetectionBlocksInnerGeometryPolygonInner } from './DocumentTextDetectionBlocksInnerGeometryPolygonInner';
import {
  DocumentTextDetectionBlocksInnerGeometryPolygonInnerFromJSON,
  DocumentTextDetectionBlocksInnerGeometryPolygonInnerFromJSONTyped,
  DocumentTextDetectionBlocksInnerGeometryPolygonInnerToJSON,
} from './DocumentTextDetectionBlocksInnerGeometryPolygonInner';

/**
 *
 * @export
 * @interface DocumentTextDetectionBlocksInnerGeometry
 */
export interface DocumentTextDetectionBlocksInnerGeometry {
  /**
   *
   * @type {DocumentTextDetectionBlocksInnerGeometryBoundingBox}
   * @memberof DocumentTextDetectionBlocksInnerGeometry
   */
  boundingBox?: DocumentTextDetectionBlocksInnerGeometryBoundingBox;
  /**
   *
   * @type {Array<DocumentTextDetectionBlocksInnerGeometryPolygonInner>}
   * @memberof DocumentTextDetectionBlocksInnerGeometry
   */
  polygon?: Array<DocumentTextDetectionBlocksInnerGeometryPolygonInner>;
}

/**
 * Check if a given object implements the DocumentTextDetectionBlocksInnerGeometry interface.
 */
export function instanceOfDocumentTextDetectionBlocksInnerGeometry(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentTextDetectionBlocksInnerGeometryFromJSON(
  json: any
): DocumentTextDetectionBlocksInnerGeometry {
  return DocumentTextDetectionBlocksInnerGeometryFromJSONTyped(json, false);
}

export function DocumentTextDetectionBlocksInnerGeometryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextDetectionBlocksInnerGeometry {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    boundingBox: !exists(json, 'BoundingBox')
      ? undefined
      : DocumentTextDetectionBlocksInnerGeometryBoundingBoxFromJSON(
          json['BoundingBox']
        ),
    polygon: !exists(json, 'Polygon')
      ? undefined
      : (json['Polygon'] as Array<any>).map(
          DocumentTextDetectionBlocksInnerGeometryPolygonInnerFromJSON
        ),
  };
}

export function DocumentTextDetectionBlocksInnerGeometryToJSON(
  value?: DocumentTextDetectionBlocksInnerGeometry | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    BoundingBox: DocumentTextDetectionBlocksInnerGeometryBoundingBoxToJSON(
      value.boundingBox
    ),
    Polygon:
      value.polygon === undefined
        ? undefined
        : (value.polygon as Array<any>).map(
            DocumentTextDetectionBlocksInnerGeometryPolygonInnerToJSON
          ),
  };
}
