/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentTextDetectionDataInnerGeometryPolygonInner
 */
export interface DocumentTextDetectionDataInnerGeometryPolygonInner {
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionDataInnerGeometryPolygonInner
   */
  x?: number;
  /**
   *
   * @type {number}
   * @memberof DocumentTextDetectionDataInnerGeometryPolygonInner
   */
  y?: number;
}

/**
 * Check if a given object implements the DocumentTextDetectionDataInnerGeometryPolygonInner interface.
 */
export function instanceOfDocumentTextDetectionDataInnerGeometryPolygonInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function DocumentTextDetectionDataInnerGeometryPolygonInnerFromJSON(
  json: any
): DocumentTextDetectionDataInnerGeometryPolygonInner {
  return DocumentTextDetectionDataInnerGeometryPolygonInnerFromJSONTyped(
    json,
    false
  );
}

export function DocumentTextDetectionDataInnerGeometryPolygonInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentTextDetectionDataInnerGeometryPolygonInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    x: !exists(json, 'X') ? undefined : json['X'],
    y: !exists(json, 'Y') ? undefined : json['Y'],
  };
}

export function DocumentTextDetectionDataInnerGeometryPolygonInnerToJSON(
  value?: DocumentTextDetectionDataInnerGeometryPolygonInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    X: value.x,
    Y: value.y,
  };
}
