/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DrawingData
 */
export interface DrawingData {
  /**
   *
   * @type {string}
   * @memberof DrawingData
   */
  type: DrawingDataTypeEnum;
  /**
   * name of SVG shape
   * @type {string}
   * @memberof DrawingData
   */
  shape: string;
  /**
   * SVG element attributes
   * @type {object}
   * @memberof DrawingData
   */
  attributes: object;
}

/**
 * @export
 */
export const DrawingDataTypeEnum = {
  Drawing: 'drawing',
} as const;
export type DrawingDataTypeEnum =
  (typeof DrawingDataTypeEnum)[keyof typeof DrawingDataTypeEnum];

/**
 * Check if a given object implements the DrawingData interface.
 */
export function instanceOfDrawingData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'type' in value;
  isInstance = isInstance && 'shape' in value;
  isInstance = isInstance && 'attributes' in value;

  return isInstance;
}

export function DrawingDataFromJSON(json: any): DrawingData {
  return DrawingDataFromJSONTyped(json, false);
}

export function DrawingDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DrawingData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json['type'],
    shape: json['shape'],
    attributes: json['attributes'],
  };
}

export function DrawingDataToJSON(value?: DrawingData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    shape: value.shape,
    attributes: value.attributes,
  };
}
