/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ErrorResponseData
 */
export interface ErrorResponseData {
  /**
   *
   * @type {string}
   * @memberof ErrorResponseData
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof ErrorResponseData
   */
  error?: string;
}

/**
 * Check if a given object implements the ErrorResponseData interface.
 */
export function instanceOfErrorResponseData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ErrorResponseDataFromJSON(json: any): ErrorResponseData {
  return ErrorResponseDataFromJSONTyped(json, false);
}

export function ErrorResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ErrorResponseData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: json['message'],
    error: !exists(json, 'error') ? undefined : json['error'],
  };
}

export function ErrorResponseDataToJSON(value?: ErrorResponseData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    error: value.error,
  };
}
