/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ForgotPasswordRequest
 */
export interface ForgotPasswordRequest {
  /**
   *
   * @type {string}
   * @memberof ForgotPasswordRequest
   */
  username: string;
}

/**
 * Check if a given object implements the ForgotPasswordRequest interface.
 */
export function instanceOfForgotPasswordRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'username' in value;

  return isInstance;
}

export function ForgotPasswordRequestFromJSON(
  json: any
): ForgotPasswordRequest {
  return ForgotPasswordRequestFromJSONTyped(json, false);
}

export function ForgotPasswordRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ForgotPasswordRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json['username'],
  };
}

export function ForgotPasswordRequestToJSON(
  value?: ForgotPasswordRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
  };
}
