/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
  ChatMessageFromJSON,
  ChatMessageFromJSONTyped,
  ChatMessageToJSON,
} from './ChatMessage';

/**
 *
 * @export
 * @interface GetChatSession200Response
 */
export interface GetChatSession200Response {
  /**
   *
   * @type {Array<ChatMessage>}
   * @memberof GetChatSession200Response
   */
  data: Array<ChatMessage>;
  /**
   *
   * @type {string}
   * @memberof GetChatSession200Response
   */
  sessionId: string;
}

/**
 * Check if a given object implements the GetChatSession200Response interface.
 */
export function instanceOfGetChatSession200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'sessionId' in value;

  return isInstance;
}

export function GetChatSession200ResponseFromJSON(
  json: any
): GetChatSession200Response {
  return GetChatSession200ResponseFromJSONTyped(json, false);
}

export function GetChatSession200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetChatSession200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(ChatMessageFromJSON),
    sessionId: json['sessionId'],
  };
}

export function GetChatSession200ResponseToJSON(
  value?: GetChatSession200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(ChatMessageToJSON),
    sessionId: value.sessionId,
  };
}
