/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetDocumentAttributes200Response
 */
export interface GetDocumentAttributes200Response {
  /**
   * Object containing all attributes associated with the document.
   * @type {object}
   * @memberof GetDocumentAttributes200Response
   */
  attributes?: object;
}

/**
 * Check if a given object implements the GetDocumentAttributes200Response interface.
 */
export function instanceOfGetDocumentAttributes200Response(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetDocumentAttributes200ResponseFromJSON(
  json: any
): GetDocumentAttributes200Response {
  return GetDocumentAttributes200ResponseFromJSONTyped(json, false);
}

export function GetDocumentAttributes200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetDocumentAttributes200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    attributes: !exists(json, 'attributes') ? undefined : json['attributes'],
  };
}

export function GetDocumentAttributes200ResponseToJSON(
  value?: GetDocumentAttributes200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    attributes: value.attributes,
  };
}
