/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetSessionList200ResponseInner
 */
export interface GetSessionList200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof GetSessionList200ResponseInner
   */
  sessionId?: string;
  /**
   *
   * @type {Date}
   * @memberof GetSessionList200ResponseInner
   */
  createdAt?: Date;
}

/**
 * Check if a given object implements the GetSessionList200ResponseInner interface.
 */
export function instanceOfGetSessionList200ResponseInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetSessionList200ResponseInnerFromJSON(
  json: any
): GetSessionList200ResponseInner {
  return GetSessionList200ResponseInnerFromJSONTyped(json, false);
}

export function GetSessionList200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetSessionList200ResponseInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sessionId: !exists(json, 'sessionId') ? undefined : json['sessionId'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
  };
}

export function GetSessionList200ResponseInnerToJSON(
  value?: GetSessionList200ResponseInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sessionId: value.sessionId,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
  };
}
