/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetSpaceOverview200ResponseData
 */
export interface GetSpaceOverview200ResponseData {
  /**
   *
   * @type {number}
   * @memberof GetSpaceOverview200ResponseData
   */
  documentCount?: number;
  /**
   *
   * @type {number}
   * @memberof GetSpaceOverview200ResponseData
   */
  tagCount?: number;
  /**
   *
   * @type {number}
   * @memberof GetSpaceOverview200ResponseData
   */
  attributeCount?: number;
}

/**
 * Check if a given object implements the GetSpaceOverview200ResponseData interface.
 */
export function instanceOfGetSpaceOverview200ResponseData(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetSpaceOverview200ResponseDataFromJSON(
  json: any
): GetSpaceOverview200ResponseData {
  return GetSpaceOverview200ResponseDataFromJSONTyped(json, false);
}

export function GetSpaceOverview200ResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetSpaceOverview200ResponseData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    documentCount: !exists(json, 'documentCount')
      ? undefined
      : json['documentCount'],
    tagCount: !exists(json, 'tagCount') ? undefined : json['tagCount'],
    attributeCount: !exists(json, 'attributeCount')
      ? undefined
      : json['attributeCount'],
  };
}

export function GetSpaceOverview200ResponseDataToJSON(
  value?: GetSpaceOverview200ResponseData | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    documentCount: value.documentCount,
    tagCount: value.tagCount,
    attributeCount: value.attributeCount,
  };
}
