/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetSpaceOverview200ResponseData } from './GetSpaceOverview200ResponseData';
import {
  GetSpaceOverview200ResponseDataFromJSON,
  GetSpaceOverview200ResponseDataFromJSONTyped,
  GetSpaceOverview200ResponseDataToJSON,
} from './GetSpaceOverview200ResponseData';

/**
 *
 * @export
 * @interface GetSpaceOverview200Response
 */
export interface GetSpaceOverview200Response {
  /**
   *
   * @type {GetSpaceOverview200ResponseData}
   * @memberof GetSpaceOverview200Response
   */
  data: GetSpaceOverview200ResponseData;
}

/**
 * Check if a given object implements the GetSpaceOverview200Response interface.
 */
export function instanceOfGetSpaceOverview200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;

  return isInstance;
}

export function GetSpaceOverview200ResponseFromJSON(
  json: any
): GetSpaceOverview200Response {
  return GetSpaceOverview200ResponseFromJSONTyped(json, false);
}

export function GetSpaceOverview200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetSpaceOverview200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: GetSpaceOverview200ResponseDataFromJSON(json['data']),
  };
}

export function GetSpaceOverview200ResponseToJSON(
  value?: GetSpaceOverview200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: GetSpaceOverview200ResponseDataToJSON(value.data),
  };
}
