/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface HighlightDataAreasInner
 */
export interface HighlightDataAreasInner {
  /**
   *
   * @type {string}
   * @memberof HighlightDataAreasInner
   */
  id: string;
  /**
   *
   * @type {object}
   * @memberof HighlightDataAreasInner
   */
  attributes: object;
}

/**
 * Check if a given object implements the HighlightDataAreasInner interface.
 */
export function instanceOfHighlightDataAreasInner(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'attributes' in value;

  return isInstance;
}

export function HighlightDataAreasInnerFromJSON(
  json: any
): HighlightDataAreasInner {
  return HighlightDataAreasInnerFromJSONTyped(json, false);
}

export function HighlightDataAreasInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): HighlightDataAreasInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    attributes: json['attributes'],
  };
}

export function HighlightDataAreasInnerToJSON(
  value?: HighlightDataAreasInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: value.attributes,
  };
}
