/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IntelligenceChatSessionRequest
 */
export interface IntelligenceChatSessionRequest {
  /**
   * The user message
   * @type {string}
   * @memberof IntelligenceChatSessionRequest
   */
  message: string;
}

/**
 * Check if a given object implements the IntelligenceChatSessionRequest interface.
 */
export function instanceOfIntelligenceChatSessionRequest(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function IntelligenceChatSessionRequestFromJSON(
  json: any
): IntelligenceChatSessionRequest {
  return IntelligenceChatSessionRequestFromJSONTyped(json, false);
}

export function IntelligenceChatSessionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IntelligenceChatSessionRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function IntelligenceChatSessionRequestToJSON(
  value?: IntelligenceChatSessionRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
  };
}
