/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IntelligenceAnalyzeDocumentRequest
 */
export interface IntelligenceAnalyzeDocumentRequest {
  /**
   * The relative path to the document within the space
   * @type {string}
   * @memberof IntelligenceAnalyzeDocumentRequest
   */
  documentPath?: string;
}

/**
 * Check if a given object implements the IntelligenceAnalyzeDocumentRequest interface.
 */
export function instanceOfIntelligenceAnalyzeDocumentRequest(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function IntelligenceAnalyzeDocumentRequestFromJSON(
  json: any
): IntelligenceAnalyzeDocumentRequest {
  return IntelligenceAnalyzeDocumentRequestFromJSONTyped(json, false);
}

export function IntelligenceAnalyzeDocumentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IntelligenceAnalyzeDocumentRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    documentPath: !exists(json, 'documentPath')
      ? undefined
      : json['documentPath'],
  };
}

export function IntelligenceAnalyzeDocumentRequestToJSON(
  value?: IntelligenceAnalyzeDocumentRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    documentPath: value.documentPath,
  };
}
