/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IntelligenceAnalyzeDocument200Response
 */
export interface IntelligenceAnalyzeDocument200Response {
  /**
   * The task id
   * @type {string}
   * @memberof IntelligenceAnalyzeDocument200Response
   */
  taskId: string;
}

/**
 * Check if a given object implements the IntelligenceAnalyzeDocument200Response interface.
 */
export function instanceOfIntelligenceAnalyzeDocument200Response(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && 'taskId' in value;

  return isInstance;
}

export function IntelligenceAnalyzeDocument200ResponseFromJSON(
  json: any
): IntelligenceAnalyzeDocument200Response {
  return IntelligenceAnalyzeDocument200ResponseFromJSONTyped(json, false);
}

export function IntelligenceAnalyzeDocument200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IntelligenceAnalyzeDocument200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    taskId: json['taskId'],
  };
}

export function IntelligenceAnalyzeDocument200ResponseToJSON(
  value?: IntelligenceAnalyzeDocument200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    taskId: value.taskId,
  };
}
