/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IntelligenceChatSession200Response
 */
export interface IntelligenceChatSession200Response {
  /**
   * The chat session id
   * @type {string}
   * @memberof IntelligenceChatSession200Response
   */
  sessionId: string;
  /**
   * The response message from the chat service
   * @type {string}
   * @memberof IntelligenceChatSession200Response
   */
  responseMessage: string;
}

/**
 * Check if a given object implements the IntelligenceChatSession200Response interface.
 */
export function instanceOfIntelligenceChatSession200Response(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && 'sessionId' in value;
  isInstance = isInstance && 'responseMessage' in value;

  return isInstance;
}

export function IntelligenceChatSession200ResponseFromJSON(
  json: any
): IntelligenceChatSession200Response {
  return IntelligenceChatSession200ResponseFromJSONTyped(json, false);
}

export function IntelligenceChatSession200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IntelligenceChatSession200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sessionId: json['sessionId'],
    responseMessage: json['responseMessage'],
  };
}

export function IntelligenceChatSession200ResponseToJSON(
  value?: IntelligenceChatSession200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sessionId: value.sessionId,
    responseMessage: value.responseMessage,
  };
}
