/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LayoutSettings
 */
export interface LayoutSettings {
  /**
   *
   * @type {boolean}
   * @memberof LayoutSettings
   */
  primarySidebar: boolean;
  /**
   *
   * @type {boolean}
   * @memberof LayoutSettings
   */
  secondarySidebar: boolean;
}

/**
 * Check if a given object implements the LayoutSettings interface.
 */
export function instanceOfLayoutSettings(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'primarySidebar' in value;
  isInstance = isInstance && 'secondarySidebar' in value;

  return isInstance;
}

export function LayoutSettingsFromJSON(json: any): LayoutSettings {
  return LayoutSettingsFromJSONTyped(json, false);
}

export function LayoutSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LayoutSettings {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    primarySidebar: json['primarySidebar'],
    secondarySidebar: json['secondarySidebar'],
  };
}

export function LayoutSettingsToJSON(value?: LayoutSettings | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    primarySidebar: value.primarySidebar,
    secondarySidebar: value.secondarySidebar,
  };
}
