/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PlatformGet200Response
 */
export interface PlatformGet200Response {
  /**
   * The platform of the server.
   * @type {string}
   * @memberof PlatformGet200Response
   */
  platform: string;
  /**
   * The home directory of the server.
   * @type {string}
   * @memberof PlatformGet200Response
   */
  homedir: string;
  /**
   * The path separator of the server.
   * @type {string}
   * @memberof PlatformGet200Response
   */
  pathSep: string;
  /**
   *
   * @type {Array<string>}
   * @memberof PlatformGet200Response
   */
  drives?: Array<string>;
}

/**
 * Check if a given object implements the PlatformGet200Response interface.
 */
export function instanceOfPlatformGet200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'platform' in value;
  isInstance = isInstance && 'homedir' in value;
  isInstance = isInstance && 'pathSep' in value;

  return isInstance;
}

export function PlatformGet200ResponseFromJSON(
  json: any
): PlatformGet200Response {
  return PlatformGet200ResponseFromJSONTyped(json, false);
}

export function PlatformGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PlatformGet200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    platform: json['platform'],
    homedir: json['homedir'],
    pathSep: json['pathSep'],
    drives: !exists(json, 'drives') ? undefined : json['drives'],
  };
}

export function PlatformGet200ResponseToJSON(
  value?: PlatformGet200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    platform: value.platform,
    homedir: value.homedir,
    pathSep: value.pathSep,
    drives: value.drives,
  };
}
