/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PlatformFoldersPathGet200ResponseInner
 */
export interface PlatformFoldersPathGet200ResponseInner {
  /**
   * The name of the directory.
   * @type {string}
   * @memberof PlatformFoldersPathGet200ResponseInner
   */
  name: string;
  /**
   * The full path of the directory.
   * @type {string}
   * @memberof PlatformFoldersPathGet200ResponseInner
   */
  path: string;
}

/**
 * Check if a given object implements the PlatformFoldersPathGet200ResponseInner interface.
 */
export function instanceOfPlatformFoldersPathGet200ResponseInner(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && 'name' in value;
  isInstance = isInstance && 'path' in value;

  return isInstance;
}

export function PlatformFoldersPathGet200ResponseInnerFromJSON(
  json: any
): PlatformFoldersPathGet200ResponseInner {
  return PlatformFoldersPathGet200ResponseInnerFromJSONTyped(json, false);
}

export function PlatformFoldersPathGet200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PlatformFoldersPathGet200ResponseInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    path: json['path'],
  };
}

export function PlatformFoldersPathGet200ResponseInnerToJSON(
  value?: PlatformFoldersPathGet200ResponseInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    path: value.path,
  };
}
