/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RemoveDocumentTagsRequest
 */
export interface RemoveDocumentTagsRequest {
  /**
   * Array of tags to remove from the document
   * @type {Array<string>}
   * @memberof RemoveDocumentTagsRequest
   */
  tags: Array<string>;
}

/**
 * Check if a given object implements the RemoveDocumentTagsRequest interface.
 */
export function instanceOfRemoveDocumentTagsRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'tags' in value;

  return isInstance;
}

export function RemoveDocumentTagsRequestFromJSON(
  json: any
): RemoveDocumentTagsRequest {
  return RemoveDocumentTagsRequestFromJSONTyped(json, false);
}

export function RemoveDocumentTagsRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RemoveDocumentTagsRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    tags: json['tags'],
  };
}

export function RemoveDocumentTagsRequestToJSON(
  value?: RemoveDocumentTagsRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    tags: value.tags,
  };
}
