/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SetSecretRequest
 */
export interface SetSecretRequest {
  /**
   * The key of the secret.
   * @type {string}
   * @memberof SetSecretRequest
   */
  secretKey: string;
  /**
   * The value of the secret.
   * @type {string}
   * @memberof SetSecretRequest
   */
  secretValue: string;
}

/**
 * Check if a given object implements the SetSecretRequest interface.
 */
export function instanceOfSetSecretRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'secretKey' in value;
  isInstance = isInstance && 'secretValue' in value;

  return isInstance;
}

export function SetSecretRequestFromJSON(json: any): SetSecretRequest {
  return SetSecretRequestFromJSONTyped(json, false);
}

export function SetSecretRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SetSecretRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    secretKey: json['secretKey'],
    secretValue: json['secretValue'],
  };
}

export function SetSecretRequestToJSON(value?: SetSecretRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    secretKey: value.secretKey,
    secretValue: value.secretValue,
  };
}
