/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Settings
 */
export interface Settings {
  /**
   *
   * @type {string}
   * @memberof Settings
   */
  ocrService: SettingsOcrServiceEnum;
}

/**
 * @export
 */
export const SettingsOcrServiceEnum = {
  Local: 'local',
  Remote: 'remote',
} as const;
export type SettingsOcrServiceEnum =
  (typeof SettingsOcrServiceEnum)[keyof typeof SettingsOcrServiceEnum];

/**
 * Check if a given object implements the Settings interface.
 */
export function instanceOfSettings(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'ocrService' in value;

  return isInstance;
}

export function SettingsFromJSON(json: any): Settings {
  return SettingsFromJSONTyped(json, false);
}

export function SettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Settings {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ocrService: json['ocrService'],
  };
}

export function SettingsToJSON(value?: Settings | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ocrService: value.ocrService,
  };
}
