/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Space
 */
export interface Space {
  /**
   * File system path to the space.
   * @type {string}
   * @memberof Space
   */
  path: string;
  /**
   * Name of the space.
   * @type {string}
   * @memberof Space
   */
  name: string;
  /**
   * Key of the space.
   * @type {string}
   * @memberof Space
   */
  key: string;
}

/**
 * Check if a given object implements the Space interface.
 */
export function instanceOfSpace(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'path' in value;
  isInstance = isInstance && 'name' in value;
  isInstance = isInstance && 'key' in value;

  return isInstance;
}

export function SpaceFromJSON(json: any): Space {
  return SpaceFromJSONTyped(json, false);
}

export function SpaceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Space {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    path: json['path'],
    name: json['name'],
    key: json['key'],
  };
}

export function SpaceToJSON(value?: Space | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    path: value.path,
    name: value.name,
    key: value.key,
  };
}
