/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Space } from './Space';
import { SpaceFromJSON, SpaceFromJSONTyped, SpaceToJSON } from './Space';

/**
 *
 * @export
 * @interface SpacesPostRequest
 */
export interface SpacesPostRequest {
  /**
   * Name of the space
   * @type {string}
   * @memberof SpacesPostRequest
   */
  name?: string;
  /**
   *
   * @type {Space}
   * @memberof SpacesPostRequest
   */
  data?: Space;
}

/**
 * Check if a given object implements the SpacesPostRequest interface.
 */
export function instanceOfSpacesPostRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SpacesPostRequestFromJSON(json: any): SpacesPostRequest {
  return SpacesPostRequestFromJSONTyped(json, false);
}

export function SpacesPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SpacesPostRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    data: !exists(json, 'data') ? undefined : SpaceFromJSON(json['data']),
  };
}

export function SpacesPostRequestToJSON(value?: SpacesPostRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    data: SpaceToJSON(value.data),
  };
}
