/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SpacesKeyPutRequest
 */
export interface SpacesKeyPutRequest {
  /**
   * File system path to the space.
   * @type {string}
   * @memberof SpacesKeyPutRequest
   */
  path?: string;
  /**
   * Name of the space.
   * @type {string}
   * @memberof SpacesKeyPutRequest
   */
  name?: string;
}

/**
 * Check if a given object implements the SpacesKeyPutRequest interface.
 */
export function instanceOfSpacesKeyPutRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SpacesKeyPutRequestFromJSON(json: any): SpacesKeyPutRequest {
  return SpacesKeyPutRequestFromJSONTyped(json, false);
}

export function SpacesKeyPutRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SpacesKeyPutRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    path: !exists(json, 'path') ? undefined : json['path'],
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function SpacesKeyPutRequestToJSON(
  value?: SpacesKeyPutRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    path: value.path,
    name: value.name,
  };
}
