/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Task
 */
export interface Task {
  /**
   *
   * @type {string}
   * @memberof Task
   */
  status: TaskStatusEnum;
  /**
   *
   * @type {number}
   * @memberof Task
   */
  progress: number;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  errorMessage?: string;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  errorCode?: string;
}

/**
 * @export
 */
export const TaskStatusEnum = {
  Pending: 'pending',
  Running: 'running',
  Completed: 'completed',
  Failed: 'failed',
} as const;
export type TaskStatusEnum =
  (typeof TaskStatusEnum)[keyof typeof TaskStatusEnum];

/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'status' in value;
  isInstance = isInstance && 'progress' in value;

  return isInstance;
}

export function TaskFromJSON(json: any): Task {
  return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Task {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: json['status'],
    progress: json['progress'],
    errorMessage: !exists(json, 'errorMessage')
      ? undefined
      : json['errorMessage'],
    errorCode: !exists(json, 'errorCode') ? undefined : json['errorCode'],
  };
}

export function TaskToJSON(value?: Task | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: value.status,
    progress: value.progress,
    errorMessage: value.errorMessage,
    errorCode: value.errorCode,
  };
}
