/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateSpaceRequest
 */
export interface UpdateSpaceRequest {
  /**
   * File system path to the space.
   * @type {string}
   * @memberof UpdateSpaceRequest
   */
  path?: string;
  /**
   * Name of the space.
   * @type {string}
   * @memberof UpdateSpaceRequest
   */
  name?: string;
}

/**
 * Check if a given object implements the UpdateSpaceRequest interface.
 */
export function instanceOfUpdateSpaceRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateSpaceRequestFromJSON(json: any): UpdateSpaceRequest {
  return UpdateSpaceRequestFromJSONTyped(json, false);
}

export function UpdateSpaceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateSpaceRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    path: !exists(json, 'path') ? undefined : json['path'],
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function UpdateSpaceRequestToJSON(
  value?: UpdateSpaceRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    path: value.path,
    name: value.name,
  };
}
