/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VerifyChatAPISettings200Response
 */
export interface VerifyChatAPISettings200Response {
  /**
   *
   * @type {string}
   * @memberof VerifyChatAPISettings200Response
   */
  apiKeySecretKey: string;
  /**
   *
   * @type {string}
   * @memberof VerifyChatAPISettings200Response
   */
  model?: string;
  /**
   *
   * @type {string}
   * @memberof VerifyChatAPISettings200Response
   */
  baseUrl?: string;
}

/**
 * Check if a given object implements the VerifyChatAPISettings200Response interface.
 */
export function instanceOfVerifyChatAPISettings200Response(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && 'apiKeySecretKey' in value;

  return isInstance;
}

export function VerifyChatAPISettings200ResponseFromJSON(
  json: any
): VerifyChatAPISettings200Response {
  return VerifyChatAPISettings200ResponseFromJSONTyped(json, false);
}

export function VerifyChatAPISettings200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VerifyChatAPISettings200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    apiKeySecretKey: json['apiKeySecretKey'],
    model: !exists(json, 'model') ? undefined : json['model'],
    baseUrl: !exists(json, 'baseUrl') ? undefined : json['baseUrl'],
  };
}

export function VerifyChatAPISettings200ResponseToJSON(
  value?: VerifyChatAPISettings200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    apiKeySecretKey: value.apiKeySecretKey,
    model: value.model,
    baseUrl: value.baseUrl,
  };
}
