/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VerifyChatAPISettingsRequest
 */
export interface VerifyChatAPISettingsRequest {
  /**
   * The key of the secret.
   * @type {string}
   * @memberof VerifyChatAPISettingsRequest
   */
  baseUrl?: string;
  /**
   * The value of the secret.
   * @type {string}
   * @memberof VerifyChatAPISettingsRequest
   */
  model?: string;
  /**
   * API key
   * @type {string}
   * @memberof VerifyChatAPISettingsRequest
   */
  apiKey: string;
}

/**
 * Check if a given object implements the VerifyChatAPISettingsRequest interface.
 */
export function instanceOfVerifyChatAPISettingsRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'apiKey' in value;

  return isInstance;
}

export function VerifyChatAPISettingsRequestFromJSON(
  json: any
): VerifyChatAPISettingsRequest {
  return VerifyChatAPISettingsRequestFromJSONTyped(json, false);
}

export function VerifyChatAPISettingsRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VerifyChatAPISettingsRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    baseUrl: !exists(json, 'baseUrl') ? undefined : json['baseUrl'],
    model: !exists(json, 'model') ? undefined : json['model'],
    apiKey: json['apiKey'],
  };
}

export function VerifyChatAPISettingsRequestToJSON(
  value?: VerifyChatAPISettingsRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    baseUrl: value.baseUrl,
    model: value.model,
    apiKey: value.apiKey,
  };
}
