/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { PlatformGet200Response } from '../models/index';
import {
  PlatformGet200ResponseFromJSON,
  PlatformGet200ResponseToJSON,
} from '../models/index';

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * This endpoint returns the platform and home directory information of the server.
   * Get platform information
   */
  async platformGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PlatformGet200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/platform`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PlatformGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * This endpoint returns the platform and home directory information of the server.
   * Get platform information
   */
  async platformGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PlatformGet200Response> {
    const response = await this.platformGetRaw(initOverrides);
    return await response.value();
  }
}
