/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface IntelligenceAnalyzeDocumentRequest {
  spaceKey: string;
  path: string;
  pageNum: number;
  body: string;
}

/**
 *
 */
export class IntelligenceApi extends runtime.BaseAPI {
  /**
   * analyze doucment through intelligence service
   */
  async intelligenceAnalyzeDocumentRaw(
    requestParameters: IntelligenceAnalyzeDocumentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (
      requestParameters.spaceKey === null ||
      requestParameters.spaceKey === undefined
    ) {
      throw new runtime.RequiredError(
        'spaceKey',
        'Required parameter requestParameters.spaceKey was null or undefined when calling intelligenceAnalyzeDocument.'
      );
    }

    if (
      requestParameters.path === null ||
      requestParameters.path === undefined
    ) {
      throw new runtime.RequiredError(
        'path',
        'Required parameter requestParameters.path was null or undefined when calling intelligenceAnalyzeDocument.'
      );
    }

    if (
      requestParameters.pageNum === null ||
      requestParameters.pageNum === undefined
    ) {
      throw new runtime.RequiredError(
        'pageNum',
        'Required parameter requestParameters.pageNum was null or undefined when calling intelligenceAnalyzeDocument.'
      );
    }

    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling intelligenceAnalyzeDocument.'
      );
    }

    const queryParameters: any = {};

    if (requestParameters.spaceKey !== undefined) {
      queryParameters['spaceKey'] = requestParameters.spaceKey;
    }

    if (requestParameters.path !== undefined) {
      queryParameters['path'] = requestParameters.path;
    }

    if (requestParameters.pageNum !== undefined) {
      queryParameters['pageNum'] = requestParameters.pageNum;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'text/plain';

    const response = await this.request(
      {
        path: `/intelligence/analyze_document`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters.body as any,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * analyze doucment through intelligence service
   */
  async intelligenceAnalyzeDocument(
    requestParameters: IntelligenceAnalyzeDocumentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.intelligenceAnalyzeDocumentRaw(requestParameters, initOverrides);
  }
}
