/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { DocumentTextDetectionDataInner } from '../models/index';
import {
  DocumentTextDetectionDataInnerFromJSON,
  DocumentTextDetectionDataInnerToJSON,
} from '../models/index';

export interface IntelligenceAnalyzeDocumentRequest {
  spaceKey: string;
  path: string;
  pageNum: number;
  body: string;
  mock?: number;
}

/**
 *
 */
export class IntelligenceApi extends runtime.BaseAPI {
  /**
   * analyze doucment through intelligence service
   */
  async intelligenceAnalyzeDocumentRaw(
    requestParameters: IntelligenceAnalyzeDocumentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<DocumentTextDetectionDataInner>>> {
    if (
      requestParameters.spaceKey === null ||
      requestParameters.spaceKey === undefined
    ) {
      throw new runtime.RequiredError(
        'spaceKey',
        'Required parameter requestParameters.spaceKey was null or undefined when calling intelligenceAnalyzeDocument.'
      );
    }

    if (
      requestParameters.path === null ||
      requestParameters.path === undefined
    ) {
      throw new runtime.RequiredError(
        'path',
        'Required parameter requestParameters.path was null or undefined when calling intelligenceAnalyzeDocument.'
      );
    }

    if (
      requestParameters.pageNum === null ||
      requestParameters.pageNum === undefined
    ) {
      throw new runtime.RequiredError(
        'pageNum',
        'Required parameter requestParameters.pageNum was null or undefined when calling intelligenceAnalyzeDocument.'
      );
    }

    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling intelligenceAnalyzeDocument.'
      );
    }

    const queryParameters: any = {};

    if (requestParameters.path !== undefined) {
      queryParameters['path'] = requestParameters.path;
    }

    if (requestParameters.pageNum !== undefined) {
      queryParameters['pageNum'] = requestParameters.pageNum;
    }

    if (requestParameters.mock !== undefined) {
      queryParameters['mock'] = requestParameters.mock;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'text/plain';

    const response = await this.request(
      {
        path: `/intelligence/{spaceKey}/analyze`.replace(
          `{${'spaceKey'}}`,
          encodeURIComponent(String(requestParameters.spaceKey))
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters.body as any,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DocumentTextDetectionDataInnerFromJSON)
    );
  }

  /**
   * analyze doucment through intelligence service
   */
  async intelligenceAnalyzeDocument(
    requestParameters: IntelligenceAnalyzeDocumentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<DocumentTextDetectionDataInner>> {
    const response = await this.intelligenceAnalyzeDocumentRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
