/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  PlatformDirectoriesPathGet200ResponseInner,
  PlatformGet200Response,
} from '../models/index';
import {
  PlatformDirectoriesPathGet200ResponseInnerFromJSON,
  PlatformDirectoriesPathGet200ResponseInnerToJSON,
  PlatformGet200ResponseFromJSON,
  PlatformGet200ResponseToJSON,
} from '../models/index';

export interface PlatformDirectoriesPathGetRequest {
  path: string;
}

/**
 *
 */
export class PlatformApi extends runtime.BaseAPI {
  /**
   * This endpoint returns a list of directories in the specified path.
   * List directories of a specified path
   */
  async platformDirectoriesPathGetRaw(
    requestParameters: PlatformDirectoriesPathGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<
    runtime.ApiResponse<Array<PlatformDirectoriesPathGet200ResponseInner>>
  > {
    if (
      requestParameters.path === null ||
      requestParameters.path === undefined
    ) {
      throw new runtime.RequiredError(
        'path',
        'Required parameter requestParameters.path was null or undefined when calling platformDirectoriesPathGet.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/platform/directories/{path}`.replace(
          `{${'path'}}`,
          encodeURIComponent(String(requestParameters.path))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PlatformDirectoriesPathGet200ResponseInnerFromJSON)
    );
  }

  /**
   * This endpoint returns a list of directories in the specified path.
   * List directories of a specified path
   */
  async platformDirectoriesPathGet(
    requestParameters: PlatformDirectoriesPathGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<PlatformDirectoriesPathGet200ResponseInner>> {
    const response = await this.platformDirectoriesPathGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * This endpoint returns the platform and home directory information of the server.
   * Get platform information
   */
  async platformGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PlatformGet200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/platform`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PlatformGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * This endpoint returns the platform and home directory information of the server.
   * Get platform information
   */
  async platformGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PlatformGet200Response> {
    const response = await this.platformGetRaw(initOverrides);
    return await response.value();
  }
}
