/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  GetSpaceOverview200Response,
  ReindexSpace200Response,
  SearchDocuments200Response,
} from '../models/index';
import {
  GetSpaceOverview200ResponseFromJSON,
  GetSpaceOverview200ResponseToJSON,
  ReindexSpace200ResponseFromJSON,
  ReindexSpace200ResponseToJSON,
  SearchDocuments200ResponseFromJSON,
  SearchDocuments200ResponseToJSON,
} from '../models/index';

export interface GetSpaceOverviewRequest {
  spaceKey: string;
}

export interface ReindexSpaceRequest {
  spaceKey: string;
}

export interface SearchDocumentsRequest {
  spaceKey: string;
  tagFilter?: Array<string>;
  attributeFilters?: string;
  offset?: number;
  limit?: number;
}

/**
 *
 */
export class SearchApi extends runtime.BaseAPI {
  /**
   * Get overview of a space
   */
  async getSpaceOverviewRaw(
    requestParameters: GetSpaceOverviewRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetSpaceOverview200Response>> {
    if (
      requestParameters.spaceKey === null ||
      requestParameters.spaceKey === undefined
    ) {
      throw new runtime.RequiredError(
        'spaceKey',
        'Required parameter requestParameters.spaceKey was null or undefined when calling getSpaceOverview.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/search/{spaceKey}/overview`.replace(
          `{${'spaceKey'}}`,
          encodeURIComponent(String(requestParameters.spaceKey))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetSpaceOverview200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get overview of a space
   */
  async getSpaceOverview(
    requestParameters: GetSpaceOverviewRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetSpaceOverview200Response> {
    const response = await this.getSpaceOverviewRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Reindex a space
   */
  async reindexSpaceRaw(
    requestParameters: ReindexSpaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ReindexSpace200Response>> {
    if (
      requestParameters.spaceKey === null ||
      requestParameters.spaceKey === undefined
    ) {
      throw new runtime.RequiredError(
        'spaceKey',
        'Required parameter requestParameters.spaceKey was null or undefined when calling reindexSpace.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/search/{spaceKey}/reindex`.replace(
          `{${'spaceKey'}}`,
          encodeURIComponent(String(requestParameters.spaceKey))
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ReindexSpace200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Reindex a space
   */
  async reindexSpace(
    requestParameters: ReindexSpaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ReindexSpace200Response> {
    const response = await this.reindexSpaceRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Search documents in a specific space
   */
  async searchDocumentsRaw(
    requestParameters: SearchDocumentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<SearchDocuments200Response>> {
    if (
      requestParameters.spaceKey === null ||
      requestParameters.spaceKey === undefined
    ) {
      throw new runtime.RequiredError(
        'spaceKey',
        'Required parameter requestParameters.spaceKey was null or undefined when calling searchDocuments.'
      );
    }

    const queryParameters: any = {};

    if (requestParameters.tagFilter) {
      queryParameters['tagFilter'] = requestParameters.tagFilter;
    }

    if (requestParameters.attributeFilters !== undefined) {
      queryParameters['attributeFilters'] = requestParameters.attributeFilters;
    }

    if (requestParameters.offset !== undefined) {
      queryParameters['offset'] = requestParameters.offset;
    }

    if (requestParameters.limit !== undefined) {
      queryParameters['limit'] = requestParameters.limit;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/search/{spaceKey}/documents`.replace(
          `{${'spaceKey'}}`,
          encodeURIComponent(String(requestParameters.spaceKey))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SearchDocuments200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Search documents in a specific space
   */
  async searchDocuments(
    requestParameters: SearchDocumentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<SearchDocuments200Response> {
    const response = await this.searchDocumentsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
