/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  CreateSpaceOperationType,
  CreateSpaceRequest,
  DocumentTag,
  Space,
  UpdateSpaceRequest,
} from '../models/index';
import {
  CreateSpaceOperationTypeFromJSON,
  CreateSpaceOperationTypeToJSON,
  CreateSpaceRequestFromJSON,
  CreateSpaceRequestToJSON,
  DocumentTagFromJSON,
  DocumentTagToJSON,
  SpaceFromJSON,
  SpaceToJSON,
  UpdateSpaceRequestFromJSON,
  UpdateSpaceRequestToJSON,
} from '../models/index';

export interface CreateSpaceOperationRequest {
  createSpaceRequest: CreateSpaceRequest;
  type?: CreateSpaceOperationType;
}

export interface DeleteSpaceRequest {
  key: string;
}

export interface GetSpaceDocumentTagsRequest {
  key: string;
}

export interface UpdateSpaceOperationRequest {
  key: string;
  updateSpaceRequest: UpdateSpaceRequest;
}

/**
 *
 */
export class SpacesApi extends runtime.BaseAPI {
  /**
   * Create a new space
   */
  async createSpaceRaw(
    requestParameters: CreateSpaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (
      requestParameters.createSpaceRequest === null ||
      requestParameters.createSpaceRequest === undefined
    ) {
      throw new runtime.RequiredError(
        'createSpaceRequest',
        'Required parameter requestParameters.createSpaceRequest was null or undefined when calling createSpace.'
      );
    }

    const queryParameters: any = {};

    if (requestParameters.type !== undefined) {
      queryParameters['type'] = requestParameters.type;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/spaces`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateSpaceRequestToJSON(requestParameters.createSpaceRequest),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Create a new space
   */
  async createSpace(
    requestParameters: CreateSpaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.createSpaceRaw(requestParameters, initOverrides);
  }

  /**
   * Delete an existing space
   */
  async deleteSpaceRaw(
    requestParameters: DeleteSpaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling deleteSpace.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/spaces/{key}`.replace(
          `{${'key'}}`,
          encodeURIComponent(String(requestParameters.key))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete an existing space
   */
  async deleteSpace(
    requestParameters: DeleteSpaceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteSpaceRaw(requestParameters, initOverrides);
  }

  /**
   * Get all document tags of a space
   */
  async getSpaceDocumentTagsRaw(
    requestParameters: GetSpaceDocumentTagsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<DocumentTag>>> {
    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling getSpaceDocumentTags.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/spaces/{key}/tags`.replace(
          `{${'key'}}`,
          encodeURIComponent(String(requestParameters.key))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DocumentTagFromJSON)
    );
  }

  /**
   * Get all document tags of a space
   */
  async getSpaceDocumentTags(
    requestParameters: GetSpaceDocumentTagsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<DocumentTag>> {
    const response = await this.getSpaceDocumentTagsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Get all spaces
   */
  async getSpacesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Space>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/spaces`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(SpaceFromJSON)
    );
  }

  /**
   * Get all spaces
   */
  async getSpaces(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Space>> {
    const response = await this.getSpacesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Update an existing space
   */
  async updateSpaceRaw(
    requestParameters: UpdateSpaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling updateSpace.'
      );
    }

    if (
      requestParameters.updateSpaceRequest === null ||
      requestParameters.updateSpaceRequest === undefined
    ) {
      throw new runtime.RequiredError(
        'updateSpaceRequest',
        'Required parameter requestParameters.updateSpaceRequest was null or undefined when calling updateSpace.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/spaces/{key}`.replace(
          `{${'key'}}`,
          encodeURIComponent(String(requestParameters.key))
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateSpaceRequestToJSON(requestParameters.updateSpaceRequest),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Update an existing space
   */
  async updateSpace(
    requestParameters: UpdateSpaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.updateSpaceRaw(requestParameters, initOverrides);
  }
}
