/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ListDirectories200ResponseInner,
  PlatformInfo200Response,
} from '../models/index';
import {
  ListDirectories200ResponseInnerFromJSON,
  ListDirectories200ResponseInnerToJSON,
  PlatformInfo200ResponseFromJSON,
  PlatformInfo200ResponseToJSON,
} from '../models/index';

export interface ListDirectoriesRequest {
  path: string;
}

/**
 *
 */
export class SystemApi extends runtime.BaseAPI {
  /**
   * This endpoint returns a list of directories in the specified path.
   * List directories of a specified path
   */
  async listDirectoriesRaw(
    requestParameters: ListDirectoriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<ListDirectories200ResponseInner>>> {
    if (
      requestParameters.path === null ||
      requestParameters.path === undefined
    ) {
      throw new runtime.RequiredError(
        'path',
        'Required parameter requestParameters.path was null or undefined when calling listDirectories.'
      );
    }

    const queryParameters: any = {};

    if (requestParameters.path !== undefined) {
      queryParameters['path'] = requestParameters.path;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/system/directories`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ListDirectories200ResponseInnerFromJSON)
    );
  }

  /**
   * This endpoint returns a list of directories in the specified path.
   * List directories of a specified path
   */
  async listDirectories(
    requestParameters: ListDirectoriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<ListDirectories200ResponseInner>> {
    const response = await this.listDirectoriesRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * This endpoint returns the platform and home directory information of the server.
   * Get platform information
   */
  async platformInfoRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PlatformInfo200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/system/platform`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PlatformInfo200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * This endpoint returns the platform and home directory information of the server.
   * Get platform information
   */
  async platformInfo(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PlatformInfo200Response> {
    const response = await this.platformInfoRaw(initOverrides);
    return await response.value();
  }
}
