/* tslint:disable */
/* eslint-disable */
/**
 * InkStain
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Task } from '../models/index';
import { TaskFromJSON, TaskToJSON } from '../models/index';

export interface GetTaskStatusRequest {
  id: string;
}

/**
 *
 */
export class TasksApi extends runtime.BaseAPI {
  /**
   * Get the progress of a task
   */
  async getTaskStatusRaw(
    requestParameters: GetTaskStatusRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Task>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling getTaskStatus.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tasks/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskFromJSON(jsonValue)
    );
  }

  /**
   * Get the progress of a task
   */
  async getTaskStatus(
    requestParameters: GetTaskStatusRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Task> {
    const response = await this.getTaskStatusRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
