name: Main CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: build
        run: npm run build
      - name: e2e test
        run: npm run e2e

  cypress-run-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: build
        run: npm run build
      - name: e2e test
        run: npm run e2e
