name: Main CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: dist

  cypress-run:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: Cypress run
        run: npx nx run cypress:e2e

  cypress-run-windows:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: Cypress run
        run: npx nx run cypress:e2e
