name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        run: npm run build

      # Zip the build output
      - name: Zip build output
        run: |
          cd dist  
          rm -rf lib
          zip -r ../dist.zip .
          cd ..

      # Create the release
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${TAG#v}" \
              -F CHANGELOG.md \
              dist.zip
